"""Constants for the CoinGecko integration."""

DOMAIN = "coingecko"
DEFAULT_SCAN_INTERVAL = 900  # 15 minutes in seconds

# API Configuration
API_BASE_URL = "https://api.coingecko.com/api/v3"
SIMPLE_PRICE_ENDPOINT = "/simple/price"

# Configuration keys
CONF_SCAN_INTERVAL = "scan_interval"
CONF_TRADING_PAIRS = "trading_pairs"

# Common coin mappings (symbol -> CoinGecko ID)
COIN_MAPPINGS = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "ADA": "cardano",
    "DOT": "polkadot",
    "LINK": "chainlink",
    "LTC": "litecoin",
    "BCH": "bitcoin-cash",
    "XRP": "ripple",
    "DOGE": "dogecoin",
    "SHIB": "shiba-inu",
    "MATIC": "matic-network",
    "AVAX": "avalanche-2",
    "SOL": "solana",
    "ATOM": "cosmos",
    "ALGO": "algorand",
    "VET": "vechain",
    "ICP": "internet-computer",
    "FIL": "filecoin",
    "TRX": "tron",
    "USDT": "tether",
    "EOS": "eos",
    "XLM": "stellar",
    "XTZ": "tezos",
    "AAVE": "aave",
    "UNI": "uniswap",
    "SUSHI": "sushi",
    "COMP": "compound-governance-token",
    "YFI": "yearn-finance",
    "SNX": "havven",
    "MKR": "maker",
    "CRV": "curve-dao-token",
    "1INCH": "1inch",
    "BAT": "basic-attention-token",
    "ZRX": "0x",
    "ENJ": "enjincoin",
    "MANA": "decentraland",
    "SAND": "the-sandbox",
    "AXS": "axie-infinity",
    "CHZ": "chiliz",
    "FLOW": "flow",
    "THETA": "theta-token",
    "FTM": "fantom",
    "NEAR": "near",
    "HBAR": "hedera-hashgraph",
    "EGLD": "elrond-erd-2",
    "KSM": "kusama",
    "DASH": "dash",
    "ZEC": "zcash",
    "XMR": "monero",
    "NEO": "neo",
    "QTUM": "qtum",
    "IOTA": "iota",
    "ONT": "ontology",
    "ZIL": "zilliqa",
    "ICX": "icon",
    "WAVES": "waves",
    "OMG": "omg",
    "NANO": "nano",
    "SC": "siacoin",
    "DGB": "digibyte",
    "RVN": "ravencoin",
    "DCR": "decred",
    "LSK": "lisk",
    "ARK": "ark",
    "REP": "augur",
    "GNT": "golem",
    "STORJ": "storj",
    "FUN": "funfair",
    "KNC": "kyber-network-crystal",
    "LRC": "loopring",
    "REQ": "request-network",
    "CVC": "civic",
    "GAS": "gas",
    "BNT": "bancor",
    "MCO": "crypto-com",
    "POA": "poa-network",
    "WTC": "waltonchain",
    "SUB": "substratum",
    "DENT": "dent",
    "HOT": "holo",
    "DOCK": "dock",
    "POLY": "polymath",
    "ELF": "aelf",
    "AION": "aion",
    "RLC": "iexec-rlc",
    "POWR": "power-ledger",
}

# Supported currencies
SUPPORTED_CURRENCIES = [
    "usd", "eur", "gbp", "jpy", "aud", "cad", "chf", "cny", "hkd", "nzd",
    "sek", "nok", "dkk", "pln", "czk", "huf", "rub", "inr", "krw", "sgd",
    "thb", "try", "zar", "mxn", "brl", "ars", "clp", "cop", "pen", "uah",
    "php", "myr", "idr", "vnd", "bdt", "pkr", "lkr", "npr", "mmk",
    "khr", "lak", "mnt", "kzt", "uzs", "amd", "azn", "gel", "kgs", "tjs",
    "tmt", "afn", "iqd", "irr", "jod", "kwd", "lbp", "omr", "qar", "sar",
    "syp", "aed", "yer", "bhd", "usdt", "usdc", "dai", "busd"
]
